name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
            bazel_flags: --config=apple_silicon

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}-${{ matrix.os }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Build all targets
        run: |
          bazel build //... \
            --verbose_failures \
            ${{ matrix.bazel_flags }}

      - name: Run tests (excluding large)
        run: |
          bazel test //... \
            --test_tag_filters=-large \
            --verbose_failures \
            --test_output=errors \
            ${{ matrix.bazel_flags }}

        # Just separate these out so they don't run if some smaller tests fail.
      - name: Run large tests
        run: |
          bazel test //... \
            --test_tag_filters=large \
            --verbose_failures \
            --test_output=errors \
            ${{ matrix.bazel_flags }} \

      - name: Upload Bazel test logs
        uses: actions/upload-artifact@v7
        if: failure() # Upload artifacts only if a step failed
        with:
          name: bazel-test-logs
          path: bazel-testlogs
