name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
            bazel_flags: --config=apple_silicon
    
    env:
      # These flags apply to all bazel build and test commands.
      COMMON_BASE_FLAGS: --verbose_failures ${{ matrix.bazel_flags }}
      # These flags apply to all bazel test commands.
      COMMON_TEST_FLAGS: --test_output=errors --test_summary=detailed ${{ env.COMMON_BASE_FLAGS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}-${{ matrix.os }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Build all targets
        run: |
          bazel build //... \
              $COMMON_BASE_FLAGS

      - name: Run tests (excluding large)
        run: |
          bazel test //... \
            --test_tag_filters=-large \
            $COMMON_TEST_FLAGS

        # Just separate these out so they don't run if some smaller tests fail.
      - name: Run large tests
        run: |
          bazel test //... \
            --test_tag_filters=large \
            $COMMON_TEST_FLAGS

